version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - arichard-info
  assignees:
  - arichard-info
  ignore:
  - dependency-name: http-proxy-middleware
    versions:
    - 1.2.1
    - 1.3.1
  - dependency-name: react-hook-form
    versions:
    - 7.0.0
    - 7.0.1
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.6
    - 7.0.7
    - 7.2.1
    - 7.2.3
    - 7.3.0
    - 7.3.1
    - 7.3.2
    - 7.3.3
  - dependency-name: webpack
    versions:
    - 5.20.0
    - 5.21.1
    - 5.21.2
    - 5.24.3
    - 5.26.0
    - 5.26.1
    - 5.26.3
    - 5.30.0
    - 5.31.0
    - 5.31.1
    - 5.31.2
    - 5.32.0
    - 5.34.0
    - 5.35.0
  - dependency-name: react-spring
    versions:
    - 9.0.0
    - 9.0.1
    - 9.1.0
    - 9.1.1
  - dependency-name: cypress
    versions:
    - 6.7.0
    - 6.7.1
    - 7.0.0
    - 7.0.1
  - dependency-name: styled-components
    versions:
    - 5.2.2
  - dependency-name: react-is
    versions:
    - 17.0.2
  - dependency-name: dotenv-webpack
    versions:
    - 6.0.1
    - 6.0.3
    - 7.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.0
  - dependency-name: html-loader
    versions:
    - 2.0.0
  - dependency-name: html-webpack-plugin
    versions:
    - 5.1.0
  - dependency-name: eslint
    versions:
    - 7.20.0
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - arichard-info
  assignees:
  - arichard-info
  ignore:
  - dependency-name: validator
    versions:
    - 13.6.0
  - dependency-name: mongoose
    versions:
    - 5.11.20
  commit-message:
    prefix: chore
    include: scope
