version: "3"
services:
  backend:
    container_name: app_server
    build:
      context: ./server
    command: npm run dev
    image: beer_app/app_server
    ports:
      - "${SERVER_PORT}:5000"
    volumes:
      - ./server:/usr/src/app
      - ./.env:/usr/src/app/.env
  frontend:
    container_name: app_client
    build:
      context: ./client
    command: npm run start
    image: beer_app/app_client
    ports:
      - "${CLIENT_PORT}:3000"
    volumes:
      - ./client:/usr/src/app
      - ./.env:/usr/src/app/.env
    depends_on:
      - backend
