version: "2"
services:
  web:
    container_name: prod_server
    environment:
      - NODE_ENV=production
    env_file: .env.production
    build: .
    ports:
      - "3000:5000"
    restart: always
