version: "2"
services:
  web:
    container_name: prod_server
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: ./docker/dockerfile/prod.node.dockerfile
    ports:
      - "3000:5000"
    restart: always
