version: "3"
services:
  database:
    container_name: app_database
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "${DATABASE_PORT:-27017}:27017"
  web:
    container_name: prod_server
    environment:
      - NODE_ENV=production
      - DATABASE=${DATABASE:-mongodb://database:27017/beer_app}
      - SERVER_URL=http://localhost:${SERVER_PORT:-5000}
      - MAIL_USER
      - MAIL_PASS
      - SECRET_JWT
      - SESSION_SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
    build:
      context: .
      dockerfile: ./docker/dockerfile/prod.node.dockerfile
    ports:
      - "5000:5000"
    restart: on-failure
    links:
      - database
