name: Docker Image CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAIL_USER: ${{ secrets.MAIL_USER }}
      MAIL_PASS: ${{ secrets.MAIL_PASS }}
      GOOGLE_CLIENT_ID: ${{ secrets.MAIL_PASS }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.MAIL_PASS }}
      SECRET_JWT: CQqMO4SNlgGHbHiovAqK
      SESSION_SECRET: Bf6Y0ZQBHwZb1DK2MbBq
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.dev.yml up -d
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: "60s"
      - name: Check running containers
        run: Check client folder
        run: ls -l client
      - name: Run cypress tests
        run: cd client && node_modules/cypress/bin/cypress run
