name: Pipeline

on: [pull_request]

jobs:
  build:
    name: Build and test PR
    runs-on: ubuntu-latest
    env:
      MAIL_USER: ${{ secrets.MAIL_USER }}
      MAIL_PASS: ${{ secrets.MAIL_PASS }}
      GOOGLE_CLIENT_ID: ${{ secrets.MAIL_PASS }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.MAIL_PASS }}
      SECRET_JWT: CQqMO4SNlgGHbHiovAqK
      SESSION_SECRET: Bf6Y0ZQBHwZb1DK2MbBq
      CYPRESS_baseUrl: http://localhost:3000
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v1
      - name: Build and start docker containers
        run: docker-compose -f docker-compose.yml up -d
      - name: Docker ps
        run: docker ps
      - name: Inject sample data
        run: docker exec prod_server npm run mongo:sample
      - name: Cypress integration tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: client
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save Cypress videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: client/cypress/videos
